### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by Jeane212** [ghostjat/php-darknet#1]
running on simple.php get error return like this

PHP Fatal error:  Uncaught FFI\Exception: Failed loading '/home/ghost/bin/c-lib/darknet-darknet_yolo_v4_pre/libdarknet.so'

any clue ? thanks

**Comment by ghostjat** [comment]
HI @fayyadhm
1. you have to compile darknet library as shared library.
2. than you have to update these line `/home/ghost/bin/c-lib/darknet-darknet_yolo_v4_pre/` as per compiled library's location in your system.
